-- DATETIME을 DATE형식으로 변환하는 방법 숙지
SELECT b.BOOK_ID,a.AUTHOR_NAME,DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE FROM BOOK AS b
JOIN AUTHOR AS a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE